<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="css.css">
</head>
<body>
<form align="right">
<input type="submit" name="submit" value="LOG OUT" id="button">
	<input type="submit" name="submit" value="HOME" id="button">
</form>
<div  style="margin-left:360px;">
<form>
	<table>
		<tr>
		<td>
		Testname:
		</td>
		<td>
		<select>
			
		</select>
		</td>
		</tr>
			<tr>
		<td>
		Enter Question:
		</td>
		<td>
		<input type="text" name="">
		</td>
		</tr>
	
		<tr>
		<td colspan="2" align="center">
			<input type="submit" name="submit" value="ADD" id="button">
		</td>
		</tr>
	</table>
</form>
</div>
<br><br><br><br><br><br><br><br><br><br>

</body>
</html>